# Generated by Django 5.0.7 on 2024-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0002_user_sex_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=3300),
        ),
    ]
