# Generated by Django 5.0.7 on 2024-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0004_user_is_anonymous_user_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
