# Generated by Django 5.0.7 on 2024-08-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0006_appuser_delete_course_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='Student', max_length=10),
        ),
    ]
