# Generated by Django 5.0.7 on 2024-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0007_alter_appuser_sex_alter_appuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Course',
                'ordering': ['-date_created'],
            },
        ),
    ]
