# Generated by Django 5.0.7 on 2024-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0008_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
