# Generated by Django 5.0.7 on 2024-09-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0009_appuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_type',
        ),
    ]
