# Generated by Django 5.0.7 on 2024-09-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMgmt', '0010_remove_appuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='sex',
        ),
    ]
